// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AstroHandlerService.Providers;

#nullable disable

namespace AstroHandlerService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AstroHandlerService.Entities.Db.EphemerisDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("JupiterDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("MarsDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("MercuryDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("MoonDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("NeptuneDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("PlutoDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("SaturnDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("SunDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("UranDegrees")
                        .HasColumnType("double precision");

                    b.Property<double?>("VenusDegrees")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EphemerisSet");
                });
#pragma warning restore 612, 618
        }
    }
}
